add security updates variable
89luca89/terrible pull request #90
Opened 2021-07-04 22:09 UTC by alegrey91

Closes #86

2021-07-06 07:52 UTC, 89luca89 requested changes
At this point we need to remove also the variables used here and eventual docs inside README

2021-07-06 22:22 UTC, alegrey91 commented
> At this point we need to remove also the variables used here and eventual docs inside README

I think it has been already removed

2021-07-07 16:21 UTC, 89luca89 commented
> > At this point we need to remove also the variables used here and eventual docs inside README
> 
> I think it has been already removed

`{{ update_command }}` is a variable, we need to remove it where it's declared

2021-07-09 07:02 UTC, 89luca89 approved these changes

2021-07-09 07:03 UTC, merged